### PR TITLE
Fix/diff temp dir usage

### PR DESCRIPTION
**Pull request by iK4tsu**
```md
Changes:
 * now every file and directory is deleted after exiting the scope
 * changed pipe usage to `pipeProcess`
 * paths are generated with `buildPath`
 * every temp file/dir is created at `tempDir`
 * every file/dir name has an unique id
 * removed casts
 * `diff` now throws a DiffException if it's exit code is `2`
 * all around clean up
```

### CODE REVIEW

**Comment by iK4tsu** [comment]
forgot to document `DiffException`

**Comment by iK4tsu** [comment]
but in the meantime see if you like these changes

**Comment by CodeMyst** [comment]
thanks for the PR, i will look at it later today.

**Comment by CodeMyst** [comment]
good job on the PR, i see nothing wrong with it!

**Pull request merged**
