### PR TITLE
doing checks on username

### PR DESCRIPTION
**Pull request by Dmunch04**
doing checks on username when creating a profile and changing the username in settings. the checks only include not allowing for illegal special characters. the allowed special characters are `-_.`
fixing issue #138

### CODE REVIEW

**Comment by CodeMyst** [comment]
could you remove the `.` from the allowed characters?

**Comment by Dmunch04** [comment]
okay. i thought it would be nice to have

**Comment by CodeMyst** [comment]
the issue would be when visiting a user's profile which has a dot in it, `/users/code.myst` is a potential issue

**Comment by Dmunch04** [comment]
hmm i see. although sites such as instagram seems to work just fine with it

**Comment by CodeMyst** [comment]
ah yeah i just looked at the standard and it seems `.` are perfectly fine in paths

**Comment by Dmunch04** [comment]
the reason it failed was because i forgot to update the unittest. oops
but want me to add `.` back in? or keep it disallowed?

**Comment by CodeMyst** [comment]
ok so then i think that `.` should be fine to have. but also thought of something else, what about disallowing sequential symbols (like ---___--__...., but code-m-y-s-t) would be fine. and also disallowing the symbols to be the start or end of the username.

thoughts on this?

**Comment by Dmunch04** [comment]
hmm. i think it should only be one of them. because the main problem is being able to be named `___-----....` etc. so just one of them will fix the issue

**Comment by CodeMyst** [comment]
but then you could be named like `.code-myst.`

**Comment by Dmunch04** [comment]
hmm yes. but i have seen some people having usernames such as fx `_codemyst`. but i guess it wont be too bad to disallow you to start or end the username with a symbol

**Pull request merged**
