### PR TITLE
Feature/add docker support

### PR DESCRIPTION
**Pull request by iK4tsu**
Added Docker support for this project.

### CODE REVIEW

**Comment by CodeMyst** [comment]
thanks for the PR! i have never used docker really so i will trust you did everything right. ill look over the changed files a bit later.

**Comment by iK4tsu** [comment]
I think I documented everything pretty well in the README.md Docker section.

**Comment by iK4tsu** [comment]
Sorry misclicked :/

**Comment by CodeMyst** [comment]
looked over the PR and everything looks fine to me. could just just please change the readme to all be lower case as that is the "stylization" of pastemyst. not a big issue though and sorry for the inconvenience 😅

**Comment by iK4tsu** [comment]
Sure no problem.

Can you mark this as `hacktoberfest-accepted`?

**Comment by CodeMyst** [comment]
yeah of course. i dont follow hacktoberfest stuff so idk how stuff works for it.

**Comment by iK4tsu** [comment]
Thank you!

I changed it back to all lower case.

**Comment by CodeMyst** [comment]
thanks for contributing to pastemyst!

**Pull request merged**
